# Generated by Django 3.0.7 on 2020-06-25 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0004_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='country',
            field=models.CharField(default='', max_length=32),
        ),
    ]
