# Generated by Django 3.0.7 on 2020-06-27 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0007_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='country',
        ),
        migrations.DeleteModel(
            name='Country',
        ),
    ]
