# Generated by Django 3.0.7 on 2020-06-29 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0009_auto_20200627_2049'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='telephone',
            field=models.CharField(default='123456', max_length=32),
        ),
    ]
