# Generated by Django 3.1.1 on 2020-10-10 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0010_user_telephone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='publisher',
        ),
        migrations.DeleteModel(
            name='Author',
        ),
        migrations.DeleteModel(
            name='Book',
        ),
        migrations.DeleteModel(
            name='Country',
        ),
        migrations.DeleteModel(
            name='Publisher',
        ),
    ]
